package fr.proline.studio.rsmexplorer.gui;

import fr.proline.studio.rsmexplorer.DataViewerTopComponent;
import javax.swing.border.TitledBorder;

/**
 *
 * @author JM235353
 */
public class ProteinGroupProteinSelectedPanel extends javax.swing.JPanel {

    /**
     * Creates new form SelectedProteinPanel
     */
    public ProteinGroupProteinSelectedPanel() {
        initComponents();
        
        DataViewerTopComponent.addPanel(proteinGroupPeptidePanel);
        DataViewerTopComponent.addPanel(proteinGroupProteinSetPanel);
    }

    public void updateTitle(String title) {
        if (title == null) {
            // set default title
            title = org.openide.util.NbBundle.getMessage(ProteinGroupProteinSelectedPanel.class, "ProteinGroupProteinSelectedPanel.border.title");
        }
        
        // Modify title border
        TitledBorder titledBorder = (javax.swing.border.TitledBorder) getBorder();
        titledBorder.setTitle(title);
        repaint();
        
        
    }
    
    /*public ProteinGroupProteinSetPanel getProteinSetPanel() {
        return proteinGroupProteinSetPanel;
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        proteinGroupProteinSetPanel = new fr.proline.studio.rsmexplorer.gui.ProteinGroupProteinSetPanel();
        proteinGroupPeptidePanel = new fr.proline.studio.rsmexplorer.gui.ProteinGroupPeptidePanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ProteinGroupProteinSelectedPanel.class, "ProteinGroupProteinSelectedPanel.border.title"))); // NOI18N
        setLayout(new java.awt.GridLayout(1, 0));

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane.setTopComponent(proteinGroupProteinSetPanel);
        splitPane.setBottomComponent(proteinGroupPeptidePanel);

        add(splitPane);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fr.proline.studio.rsmexplorer.gui.ProteinGroupPeptidePanel proteinGroupPeptidePanel;
    private fr.proline.studio.rsmexplorer.gui.ProteinGroupProteinSetPanel proteinGroupProteinSetPanel;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
